import { TkaCalendar } from './src/index.js';
import { de } from 'date-fns/locale/de';
import { addMonths } from 'date-fns/addMonths';

const events = [
    {
        "title": "Ice Diving",
        "type": "kursdaten",
        "start": "2026-04-17",
        "end": "2026-04-17",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/Ice_Diving.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/eistauchen/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4450,
            "post_author": "1",
            "post_date": "2017-04-26 16:02:11",
            "post_date_gmt": "2017-04-26 14:02:11",
            "post_content": "Du suchst eines der aufregendsten Abenteuer? Du hast es gefunden!\nIn diesem Kurs lernst du verschiedene Techniken des Eistauchens kennen und machst drei Freiwassertauchgänge in der Tageslicht-Zone. Zu den Themen des Kurses gehören:\n<ul>\n \t<li>Planung, Organsisation, Verfahren, Techniken, Probleme und Gefahren beim Eistauchen.</li>\n \t<li>Wahl des Tauchplatzes, Vorbereitung und Verfahrensweise um ein Ein-/Ausstiegsloch ins Eis zu schneiden.</li>\n \t<li>Spezielle Ausrüstung, Sicherheitsleinen, Signale, Leinenführungs- und Leinensicherungstechniken.</li>\n \t<li>Auswirkung von Kälte, Notfall-Verfahren für Sicherheitstaucher.</li>\n</ul>\nSchliess dich denen an die den Nervenkitzel suchen und unter dem Eis das Abenteuer ihres Lebens finden !\n\nTageslicht-Zone ist definiert als die Distanz zur Oberfläche von maximal 40 Metern, wobei vertikale und horizontale Entfernungen eingeschlossen sind.\n\nDie Eistauchkurse finden in der Regel anlässlich eines unserer Ice-Events statt. Kannst du an unserem Event nicht teilnehmen, ruf uns einfach an. Wir organisieren gerne was für dich.\n\n<em><strong>CHF 620.00 in Kombination mit einem Trockentauchkurs</strong></em>",
            "post_title": "Ice Diving",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "eistauchen",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2017-04-26 16:02:11",
            "post_modified_gmt": "2017-04-26 14:02:11",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/eistauchen/",
            "menu_order": 33,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-16T22:00:00.000Z",
        "endDate": "2026-04-16T22:00:00.000Z",
        "formattedStart": "17.04.2026"
    },
    {
        "title": "React Right",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/React-Right.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/emergency-first-response/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4392,
            "post_author": "1",
            "post_date": "2017-04-26 15:18:05",
            "post_date_gmt": "2017-04-26 13:18:05",
            "post_content": "Das React Right Nothelferprogramm von SSI besteht aus folgenden Basis Komponenten: Erstbeurteilung, Anwendung von Erste Hilfe und HLW, Stabilisierungstechniken und beinhaltet zwei optionale Komponenten: Sauerstoffgabe bei Tauchnotfällen und Grundkenntnisse des AED/ Defibrillator. Kursteilnehmer erhalten nach Durchführung diese Programms die SSI React Right Zertifizierung.\n\nWieso sollte man am React Right Kurs teilnehmen?\nUnfälle und Krankheiten können jeden Tag auftreten. Manche Opfer benötigen nur wenig Beistand, während andere ohne sofortige Hilfe schwere bleibende Schäden erleiden können. Der React Right Kurs zeigt dir, wie du im Ernstfall rasch und wirksam helfen kannst.",
            "post_title": "React Right inkl. Oxygen Provider",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "emergency-first-response",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2017-04-26 15:18:05",
            "post_modified_gmt": "2017-04-26 13:18:05",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/emergency-first-response/",
            "menu_order": 48,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "Deep Diver",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/Deep-Diving.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/deep-diver/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4381,
            "post_author": "1",
            "post_date": "2017-02-10 14:34:57",
            "post_date_gmt": "2017-02-10 13:34:57",
            "post_content": "Oft liegen Wracks in einer Tiefe von 30m und etwas mehr, oder du möchtest in dieser Tiefe tauchen, um dir Tiere anzusehen, die du dort wahrscheinlicher antriffst. Wie auch immer: Tieftauchen ist sicherlich einer der faszinierendsten Aspekte des Tauchens. Es erfordert jedoch auch besondere Rücksichtnahmen, Techniken und Kenntnisse, um sicherzustellen, dass du diese Tauchgänge auch genießen kannst. Der Specialty „Deep Diver\" macht dich genau mit diesen Kenntnissen vertraut.\n\nDas Programm umfasst 2 Tauchgänge, die an einem oder mehreren Tagen durchgeführt werden. Die Minimaltiefe für diese Tauchgänge beträgt 18m, die Maximaltiefe liegt bei 40m.\n\nIn der Regel absolvieren führen wir die Specialty-Kurse in heimischen Gewässern durch, die Tieftauchkurse können aber auch anlässlich eines unserer <a href=\"http://tauchschule-poseidon.ch/events/\">Italien-Events</a> stattfinden.",
            "post_title": "Deep Diving",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "deep-diver",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2017-02-10 14:34:57",
            "post_modified_gmt": "2017-02-10 13:34:57",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/deep-diver/",
            "menu_order": 53,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "Navigation",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/Navigation.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/navigation/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4457,
            "post_author": "1",
            "post_date": "2017-04-26 16:05:11",
            "post_date_gmt": "2017-04-26 14:05:11",
            "post_content": "Zu wissen, wo man sich unter Wasser befindet und wie man von einem Punkt zum anderen kommt, ein Gespür dafür zu bekommen, auf welchen Wegen und in welchen Distanzen der Tauchgang abläuft, hat enorme Vorteile. Es erleichtert die Suche nach markanten Objekten, nach Wracks oder Riffen und hilft vor allem, den Tauchgang genießen zu können, ohne sich ständig Sorgen machen zu müssen wo man sich befindet.\nWährend dieses Programms wirst du drei Tauchgänge machen, in denen du mit den Techniken, dem Grundlagenwissen, Verfahren und Instrumenten zur Navigation vertraut gemacht wirst:\n\nDer  Spezialkurs \"Navigation\" kann nach Absprache  mit dem Instruktor auf den Advanced Adventurer (AOWD) angerechnet werden.",
            "post_title": "Navigation",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "navigation",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2017-04-26 16:05:11",
            "post_modified_gmt": "2017-04-26 14:05:11",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/navigation/",
            "menu_order": 32,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "XR Gas Blender",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/Gas-Blender-Small.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/ssi-gas-blender/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4410,
            "post_author": "1",
            "post_date": "2017-04-26 15:38:00",
            "post_date_gmt": "2017-04-26 13:38:00",
            "post_content": "Im SSI Nitrox Gas Blender Kurs lernst Du, wie man auf sichere Weise selbst Nitroxmischungen herstellt. Dieser Kurs wird speziell für Taucher empfohlen, die bereits die Advanced Nitrox Zertifizierung besitzen und somit in der Lage sind nach erfolgreichem Bestehen des Kurses ihren 'Best Mix' für den jeweiligen Tauchgang selbst herzustellen. Aber auch Taucher mit einer Basic Nitrox Ausbildung profitieren von dem neu erworbenen Wissen um die Herstellung von Nitrox.",
            "post_title": "SSI Nitrox Gas Blender",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "ssi-gas-blender",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2017-04-26 15:38:00",
            "post_modified_gmt": "2017-04-26 13:38:00",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/ssi-gas-blender/",
            "menu_order": 39,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "Open Water Diver",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/pool03-1024x360.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/owd/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4378,
            "post_author": "1",
            "post_date": "2017-02-09 14:32:19",
            "post_date_gmt": "2017-02-09 13:32:19",
            "post_content": "<strong>Dies ist die Grundausbildung für das selbständige Tauchen. Während der Ausbildung zum Open Water Diver vermitteln dir unsere Instruktoren Basiskenntnisse. Schon nach den ersten Atemzügen im Pool oder Freiwasser spürst du die Freude am Tauchen in dir wachsen.</strong>\r\n\r\nNach Abschluss des Open Water Diver-Kurses bist du berechtigt, selbständig mit einem Buddy zu tauchen und deine Tauchausbildung mit Adventure- und/oder Specialty-Tauchgängen fortzusetzen - den Ausbildungen, die dich in spezifischen Bereichen des Tauchens perfektionieren.\r\n\r\nUnsere Tauchkurse sind auf <b>4 Teilnehmer limitiert</b> und du kannst unter folgenden <b>Optionen und Preisen frei wählen;</b>",
            "post_title": "Open Water Diver",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "owd",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2026-04-01 17:13:58",
            "post_modified_gmt": "2026-04-01 15:13:58",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/owd/",
            "menu_order": 54,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "Open Water Diver",
        "type": "kursdaten",
        "start": "2026-07-15",
        "end": "2026-07-15",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/pool03-1024x360.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/owd/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4378,
            "post_author": "1",
            "post_date": "2017-02-09 14:32:19",
            "post_date_gmt": "2017-02-09 13:32:19",
            "post_content": "<strong>Dies ist die Grundausbildung für das selbständige Tauchen. Während der Ausbildung zum Open Water Diver vermitteln dir unsere Instruktoren Basiskenntnisse. Schon nach den ersten Atemzügen im Pool oder Freiwasser spürst du die Freude am Tauchen in dir wachsen.</strong>\r\n\r\nNach Abschluss des Open Water Diver-Kurses bist du berechtigt, selbständig mit einem Buddy zu tauchen und deine Tauchausbildung mit Adventure- und/oder Specialty-Tauchgängen fortzusetzen - den Ausbildungen, die dich in spezifischen Bereichen des Tauchens perfektionieren.\r\n\r\nUnsere Tauchkurse sind auf <b>4 Teilnehmer limitiert</b> und du kannst unter folgenden <b>Optionen und Preisen frei wählen;</b>",
            "post_title": "Open Water Diver",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "owd",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2026-04-01 17:13:58",
            "post_modified_gmt": "2026-04-01 15:13:58",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/owd/",
            "menu_order": 54,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-07-14T22:00:00.000Z",
        "endDate": "2026-07-14T22:00:00.000Z",
        "formattedStart": "15.07.2026"
    },
    {
        "title": "Advanced Adventurer",
        "type": "kursdaten",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/Advanced-Open-Water-Diver.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/aowd/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4470,
            "post_author": "1",
            "post_date": "2017-04-26 16:16:10",
            "post_date_gmt": "2017-04-26 14:16:10",
            "post_content": "4 komplette Spezialkurse inkl. je 2 bis 3 Tauchgängen, zur Auswahl stehen die Kurse;\r\n\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/deep-diver/\">Tieftauchen</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/navigation/\">Navigation</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/suchen-bergen/\">Suchen &amp; Bergen</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/perfect-buyoancy/\">Perfekte Tarierung</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/nacht-schlechte-sicht/\">Nacht / beschränkte Sicht</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/bergsee/\">Bergsee</a>\r\n- <a href=\"http://tauchschule-poseidon.ch/kurse/enriched-air-diver/\">Nitrox</a>",
            "post_title": "Advanced Open Water Diver",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "aowd",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2026-02-27 19:59:46",
            "post_modified_gmt": "2026-02-27 18:59:46",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/?post_type=kurse&#038;p=4470",
            "menu_order": 25,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "asdadads",
        "type": "kursdaten",
        "start": "2026-05-21",
        "end": "2026-05-21",
        "image": "https://tsposeidon.ddev.site/app/uploads/2025/05/pool03-1024x360.jpg",
        "url": "https://tsposeidon.ddev.site/kurse/owd/",
        "backgroundColor": "#2563EB",
        "allDay": true,
        "isMultiDay": false,
        "parent": {
            "ID": 4378,
            "post_author": "1",
            "post_date": "2017-02-09 14:32:19",
            "post_date_gmt": "2017-02-09 13:32:19",
            "post_content": "<strong>Dies ist die Grundausbildung für das selbständige Tauchen. Während der Ausbildung zum Open Water Diver vermitteln dir unsere Instruktoren Basiskenntnisse. Schon nach den ersten Atemzügen im Pool oder Freiwasser spürst du die Freude am Tauchen in dir wachsen.</strong>\r\n\r\nNach Abschluss des Open Water Diver-Kurses bist du berechtigt, selbständig mit einem Buddy zu tauchen und deine Tauchausbildung mit Adventure- und/oder Specialty-Tauchgängen fortzusetzen - den Ausbildungen, die dich in spezifischen Bereichen des Tauchens perfektionieren.\r\n\r\nUnsere Tauchkurse sind auf <b>4 Teilnehmer limitiert</b> und du kannst unter folgenden <b>Optionen und Preisen frei wählen;</b>",
            "post_title": "Open Water Diver",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "owd",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2026-04-01 17:13:58",
            "post_modified_gmt": "2026-04-01 15:13:58",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://tsposeidon.ddev.site/kurse/owd/",
            "menu_order": 54,
            "post_type": "kurse",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "startDate": "2026-05-20T22:00:00.000Z",
        "endDate": "2026-05-20T22:00:00.000Z",
        "formattedStart": "21.05.2026"
    },
    {
        "title": "Tauchferien Curacao",
        "type": "reise",
        "start": "2026-04-29",
        "end": "2026-05-22",
        "image": false,
        "url": "https://tsposeidon.ddev.site/reise/tauchferien-curacao/",
        "backgroundColor": "#F200FF",
        "allDay": true,
        "isMultiDay": true,
        "parent": 4337,
        "startDate": "2026-04-28T22:00:00.000Z",
        "endDate": "2026-05-21T22:00:00.000Z",
        "formattedStart": "29.04.2026"
    },
    {
        "title": "Cocos Island 2024",
        "type": "reise",
        "start": "2026-05-28",
        "end": "2026-05-31",
        "image": false,
        "url": "https://tsposeidon.ddev.site/reise/cocos-island-2024/",
        "backgroundColor": "#F200FF",
        "allDay": true,
        "isMultiDay": true,
        "parent": 4338,
        "startDate": "2026-05-27T22:00:00.000Z",
        "endDate": "2026-05-30T22:00:00.000Z",
        "formattedStart": "28.05.2026"
    },
    {
        "title": "Eistauchen Arnisee",
        "type": "event",
        "start": "2026-04-14",
        "end": "2026-04-16",
        "image": false,
        "url": "https://tsposeidon.ddev.site/event/eistauchen-arnisee/",
        "backgroundColor": "#5B21B6",
        "allDay": true,
        "isMultiDay": true,
        "parent": 30370,
        "startDate": "2026-04-13T22:00:00.000Z",
        "endDate": "2026-04-15T22:00:00.000Z",
        "formattedStart": "14.04.2026"
    },
    {
        "title": "Verzasca Weekend (August)",
        "type": "event",
        "start": "2026-04-23",
        "end": "2026-04-23",
        "image": false,
        "url": "https://tsposeidon.ddev.site/event/verzasca-weekend-august-2022/",
        "backgroundColor": "#5B21B6",
        "allDay": true,
        "isMultiDay": false,
        "parent": 30380,
        "startDate": "2026-04-22T22:00:00.000Z",
        "endDate": "2026-04-22T22:00:00.000Z",
        "formattedStart": "23.04.2026"
    },
    {
        "title": "Verzasca Weekend (Oktober)",
        "type": "event",
        "start": "2026-10-09",
        "end": "2026-10-11",
        "image": false,
        "url": "https://tsposeidon.ddev.site/event/verzasca-weekend-oktober-2022/",
        "backgroundColor": "#5B21B6",
        "allDay": true,
        "isMultiDay": true,
        "parent": 30387,
        "startDate": "2026-10-08T22:00:00.000Z",
        "endDate": "2026-10-10T22:00:00.000Z",
        "formattedStart": "09.10.2026"
    },
    {
        "title": "Ligurien Weekend",
        "type": "event",
        "start": "2026-06-18",
        "end": "2026-06-21",
        "image": false,
        "url": "https://tsposeidon.ddev.site/event/ligurien-weekend-1/",
        "backgroundColor": "#5B21B6",
        "allDay": true,
        "isMultiDay": true,
        "parent": 30422,
        "startDate": "2026-06-17T22:00:00.000Z",
        "endDate": "2026-06-20T22:00:00.000Z",
        "formattedStart": "18.06.2026"
    },
    {
        "title": "Marmorerasee Weekend",
        "type": "event",
        "start": "2026-07-25",
        "end": "2026-07-26",
        "image": false,
        "url": "https://tsposeidon.ddev.site/event/marmorerasee-weekend/",
        "backgroundColor": "#5B21B6",
        "allDay": true,
        "isMultiDay": true,
        "parent": 30435,
        "startDate": "2026-07-24T22:00:00.000Z",
        "endDate": "2026-07-25T22:00:00.000Z",
        "formattedStart": "25.07.2026"
    }
];

const calendar = new TkaCalendar('#app', {
    events,
    aspectRatio: 1,
    locale: de,
    inputFormat: 'yyyy-MM-dd',
    outputFormat: 'dd.MM.yyyy',
    maxEventsDisplayed: 2,
    tooltip: true,
    weekStartsOn: 1,
    showAdjacentDays: true,
    showHeader: true,
    showWeekdayHeader: true,
    monthYearFormat: 'MMMM yyyy',
    dayNamesFormat: 'EEEEEE',
    onEventClick: (event, e) => {
        console.log('Event clicked:', event);
    },
    minDate: new Date(),
    maxDate: addMonths(new Date(), 6),
    todayBtn: true,
    theme: {
        primary: '#3b82f6',
        radius: '12px'
    },
    arrows: {
        prev: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>`,
        next: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>`
    }
});
